### ISSUE TITLE
Duplicate messages presented in error list

### ISSUE THREAD

**Issue by OGKamu** [tcunit/TcUnit#125] opened 2020-12-14 19:54 UTC
Found something which is a minor annoyance but also due to the way that I am handling my project structure. 

When running the top-level TcUnit.RUN, any additional loaded projects at the solution level will result in duplicated messages.

 ![image](https://user-images.githubusercontent.com/49678171/102127327-3ee10580-3eb1-11eb-9b0e-8b9cf54463b0.png)

The way I generated this response set was:

1. Clone down 'SimpleTcUnitExampleProject'
2. Add additional project to solution ( Solution > Add > New Project)
    * Doesn't seem to care which type, I've tried with a PLC or Twincat Project
3. Run TcUnit Project.

I can probably adjust my structure to resolve this, but its just a bit odd. Especially given that filtering the error list to the current project hides the output from TcUnit.

**Comment by sagatowski** [comment] 2020-12-14 20:08
This issue is a duplicate of https://github.com/tcunit/TcUnit/issues/92. Unfortunately this is a design issue with TwinCAT (you get the same behaviour with standard ADSLOGSTR-messages) and not TcUnit, so there is nothing that can be done with this.

**Closed** 2020-12-14 21:17 UTC
