### ISSUE TITLE
TcUnit example for running over multiple cycles - link is broken

### ISSUE THREAD

**Issue by ZigaJavornik** [tcunit/TcUnit#236] opened 2024-02-22 20:11 UTC
Not sure if this is the correct place to write this, but your webpage FAQ download for tests over multiple PLC cycles does not work, returns an error 404. Let me know if I should post this somewhere else.

![image](https://github.com/tcunit/TcUnit/assets/121696359/2eb397eb-6bf1-461f-ab90-ee2f514e3f82)

**Comment by sagatowski** [comment] 2024-02-22 20:22
Duplicate of #234.

**Closed by sagatowski** 2024-02-22 20:22 UTC

**Comment by sagatowski** [comment] 2024-02-22 20:36
Issue solved. Removed broken link to example for running tests over multiple cycles and replaced with an example in the documentation/FAQ instead.

**Comment by ZigaJavornik** [comment] 2024-02-22 21:55
Thank you for the quick response and fix Jakob :).
