### ISSUE TITLE
Double execution of TcUnit

### ISSUE THREAD

**Issue by fadamIT** [tcunit/TcUnit#246] opened 2024-08-27 06:49 UTC
I'm developing a library and I've added a second project to develop and run my unit tests. In the library I have no reference to the TcUnit library. 

![image](https://github.com/user-attachments/assets/79e95e9e-6b7d-4735-ab10-6f877831d4c9)

When I run my test project, I get this result :

![image](https://github.com/user-attachments/assets/d3d844f4-64ba-4ad4-ab9f-77161bcba326)

For the test, my test project is empty. There's just a dummy test that tests AssertTrue(Condition := TRUE, Message:= '');

To reproduce bug, I have just created un solution with 2 Twincat XAE project and try to run TcUnit in one of its.

I use version 4024.40, which I run on my developer laptop.

**Comment by sagatowski** [comment] 2024-08-27 06:52
Duplicate of https://github.com/tcunit/TcUnit/issues/92.

**Closed by sagatowski** 2024-08-27 06:52 UTC
