### ISSUE TITLE
Tests seem to run 4 times

### ISSUE THREAD

**Issue by Oleksiy1990** [tcunit/TcUnit#235] opened 2024-02-01 10:30 UTC
**Describe the bug**
When one runs the tests, it looks like the same output is produced 4 times

**To Reproduce**
What steps are necessary to reproduce the behavior?

**Expected behavior**
They should only run once and produce a single report message

**Screenshots**
![image](https://github.com/tcunit/TcUnit/assets/7410221/e0a8801c-11f0-4d0d-b80d-f1dde3d5bbd9)

**Software versions**
TcUnit 1.3, TwinCAT Build 4024.53

**Run environment**
Virtual (isolated core on the dev laptop)

**Additional context**

**Comment by sagatowski** [comment] 2024-02-02 13:07
This is not a problem with TcUnit.
Duplicate of https://github.com/tcunit/TcUnit/issues/92.

**Closed by sagatowski** 2024-02-02 13:07 UTC

**Comment by Oleksiy1990** [comment] 2024-02-02 13:25
Hi Jakob,

That's really nice info, thanks a lot!

Best regards,
Oleksiy
